version: "3.9"

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task5
    ports:
      - "5252"    # internal only — container exposes 5252 for other containers

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task5
    ports:
      - "9000"    # internal only — container exposes 9000 for other containers
    depends_on:
      - back-end

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"   # map host 80 -> container 80 (proxy)
    depends_on:
      - front-end
      - back-end
